---
title: "Untitled"
author: "Qingyue Su"
date: "1/3/2021"
output: html_document
---

```{r}
library(stargazer)
library(tidyverse)
library(knitr)
library(readr)
library(dplyr)
library(data.table)
```

### Import Data

```{r}

# read the outpatient table and the two RA codes 
#outp <- read.table('data/VTOUTP16.TXT',sep=',',header=TRUE)
outp <- read.csv("data/VTOUTP16.TXT")
#View(outp)
head(outp)
```

```{r}
ra1 <- read.csv('data/RA.csv',sep=',',header=TRUE)
#View(ra1)
head(ra1)
```

```{r}
ra2 <- read.csv('data/Other_RA.csv',sep=',',header=TRUE)
#View(ra2)
head(ra2)
```

```{r}
#rev <- read.table('/Users/apple/Desktop/hs_256/VTREVCODE16.TXT',sep=',',header=TRUE)
rev <- read.csv('data/VTREVCODE16.TXT',sep=',',header=TRUE)
#View(rev)
head(rev)
```

```{r}
#inp <- read.table('data/VTINP16_upd.TXT',sep=',',header=TRUE)
inp <- read.csv('data/VTINP16_upd.TXT',sep=',',header=TRUE)
#View(inp)
head(inp)
```

#### question 1

```{r}
ra1_code = ra1$ICD.10.Codes
ra1_code
```

```{r}
ra2_code = ra2$ICD.10.Codes
ra2_code
```

```{r}
#filter the two sub-cohorts
outp_ra1 = outp%>% filter(DX1 %in% ra1_code|DX2 %in% ra1_code|DX3 %in% ra1_code|DX4 %in% ra1_code|DX5 %in% ra1_code|DX6 %in% ra1_code|DX7 %in% ra1_code|DX8 %in% ra1_code|DX9 %in% ra1_code|DX10 %in% ra1_code|DX11 %in% ra1_code|DX12 %in% ra1_code|DX13 %in% ra1_code|DX14 %in% ra1_code|DX15 %in% ra1_code|DX16 %in% ra1_code|DX17 %in% ra1_code|DX18 %in% ra1_code|DX19 %in% ra1_code|DX20 %in% ra1_code)

head(outp_ra1)
```

```{r}
outp_ra2 = outp%>% filter(DX1 %in% ra2_code|DX2 %in% ra2_code|DX3 %in% ra2_code|DX4 %in% ra2_code|DX5 %in% ra2_code|DX6 %in% ra2_code|DX7 %in% ra2_code|DX8 %in% ra2_code|DX9 %in% ra2_code|DX10 %in% ra2_code|DX11 %in% ra2_code|DX12 %in% ra2_code|DX13 %in% ra2_code|DX14 %in% ra2_code|DX15 %in% ra2_code|DX16 %in% ra2_code|DX17 %in% ra2_code|DX18 %in% ra2_code|DX19 %in% ra2_code|DX20 %in% ra2_code)

head(outp_ra1)
```

```{r}
#step 2
#frequency of chronic RA
outp_ra1_new <- outp_ra1[,10:29]
code_frequency1 <- table(unlist(outp_ra1_new))
code_frequency1 <- data.frame(code_frequency1)
code_frequency1_t = code_frequency1 %>% filter(Var1 %in% ra1_code)%>% arrange(-Freq)

head(code_frequency1_t)
```

```{r}
#frequency of other RA
outp_ra2_new <- outp_ra2[,10:29]
code_frequency2 <- table(unlist(outp_ra2_new))
code_frequency2 <- data.frame(code_frequency2)
code_frequency2_t = code_frequency2 %>% filter(Var1 %in% ra1_code)%>% arrange(-Freq)

head(code_frequency2_t)
```

```{r}
#step 3
# gender difference of chronic RA
ra1_sex <- outp_ra1 %>% group_by(sex) %>% summarise(count=n())
# sex = 1 -> male; (ra1_male)
# sex = 2 -> female; (ra1_female)
ra1_male <- ra1_sex %>% filter(sex==1)
ra1_female <- ra1_sex %>% filter(sex==2)

ra1_sex
```

```{r}
# gender difference of other RA
ra2_sex <- outp_ra2 %>% group_by(sex) %>% summarise(count=n())
# sex = 1 -> male; (ra2_male)
# sex = 2 -> female; (ra2_female)
ra2_male <- ra2_sex %>% filter(sex==1)
ra2_female <- ra2_sex %>% filter(sex==2)

ra2_sex
```

```{r}
#2*2 table
genderdiff = matrix(c(252, 724, 14, 16),
       nrow = 2,
       dimnames = list(Gender = c("Male", "Female"),
                       RA = c("chronic", "other")))
genderdiff
```

```{r}
# fisher test
fisher.test(genderdiff, alternative = "less")
```

```{r}
#step 4
# IQR of chronic RA charges
summary(outp_ra1$CHRGS)
IQR(outp_ra1$CHRGS)
```

```{r}
# IQR of other RA charges
summary(outp_ra2$CHRGS)
IQR(outp_ra2$CHRGS)
```

#### question 2

```{r}
#view(inp)
head(inp)
```

```{r}
mdc1 = inp %>% filter(MDC=="1")
mdc14 = inp %>% filter(MDC=="14")
```

```{r}
###mdc1

#HHI of insurance company
mdc1 = data.table(mdc1)
table(mdc1$hnum2)
```

```{r}
share = round(prop.table(table(mdc1$hnum2)), digits = 3)
share = data.frame(share)
HHI <- function(x){
  return(sum(x^2))
}
HHI(share$Freq)
#0.4065
```

```{r}
#HHI by admissions
admissions = tapply(unique(mdc1$UNIQ),mdc1$hnum2,length)
totalad = sum(admissions)
share2 =lapply(admissions,function(x)x/totalad)
HHI(unlist(share2))
#0.4070
```

```{r}
# HHI by charges
mdc1 = mdc1 %>% filter(is.na(CHRGS) == FALSE)
charge = tapply(mdc1$CHRGS,mdc1$hnum2,sum)
total = sum(charge)
share3 =lapply(charge,function(x)x/total)
HHI(unlist(share3))
#0.6368
```

```{r}
###mdc14

#HHI of insurance company
mdc14 = data.table(mdc14)
table(mdc14$hnum2)
```

```{r}
share4 = round(prop.table(table(mdc14$hnum2)), digits = 3)
share4 = data.frame(share4)
HHI(share4$Freq)
#0.2142
```

```{r}
#HHI by admissions
admissions = tapply(unique(mdc14$UNIQ),mdc14$hnum2,length)
totalad = sum(admissions)
share5 =lapply(admissions,function(x)x/totalad)
HHI(unlist(share5))
#0.2141
```

```{r}
# by charges
charge = tapply(mdc14$CHRGS,mdc14$hnum2,sum)
total = sum(charge)
share6 =lapply(charge,function(x)x/total)
HHI(unlist(share6))
#0.2453
```

```{r}
#conclusion
#mdc1 is more concentrated
share %>% arrange(-Freq)
# lion share:5:University of Vermont Medical Center (as of 2014)
```

```{r}
# for admission, the lion gets 62.24%
unlist(share2)
```

```{r}
# for charges, the lion gets 79.27%
unlist(share3)
```

